(() => {
  'use strict';
  const BUILD='CENTRAL190-0190-F13-20260613-1259-BRT';
  let state=C190_Save.load(); let tickTimer=null;
  const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function toast(message,type='success'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toastRegion').appendChild(el);setTimeout(()=>el.remove(),3500);}
  function persist(){C190_Save.save(state);renderAll();}
  function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));$('#sidebar').classList.remove('open');$('#mainContent').scrollTop=0;window.scrollTo(0,0);const labels={dashboard:'Comando operacional',dispatch:'Plantão contínuo',career:'Progressão profissional',training:'Capacitação',goals:'Metas de carreira',achievements:'Reconhecimento',reports:'Histórico operacional',settings:'Sistema e segurança'};$('#screenSubtitle').textContent=labels[name]||'Central 190';renderAll();}
  function rank(){return C190_Career.ranks[C190_Career.rankIndex(state.career.rankId)];}
  function renderDashboard(){const has=!!state.profile;$('#careerSetup').hidden=has;$('#dashboardContent').hidden=!has;if(!has)return;const r=rank();$('#welcomeTitle').textContent=`${state.profile.callSign} · ${state.profile.name}`;$('#careerSummary').textContent=`${r.name} · dificuldade ${state.profile.difficulty} · ${state.career.completedCourses.length} curso(s) concluído(s)`;$('#rankIcon').textContent=r.icon;$('#rankName').textContent=r.name;$('#metricReputation').textContent=state.career.reputation;$('#repBar').style.width=`${state.career.reputation}%`;$('#metricXp').textContent=`${state.career.xp} XP`;const p=C190_Career.getPromotionStatus(state);const nextXp=p.next?.xp||state.career.xp;$('#xpBar').style.width=`${Math.min(100,nextXp?state.career.xp/nextXp*100:100)}%`;$('#metricShifts').textContent=state.career.totalShifts;$('#metricResolved').textContent=`${state.career.totalResolved} atendimentos`;const w=C190_Career.activeWarnings(state);$('#metricWarnings').textContent=w?`${w} ativa(s)`:'Sem advertências';$('#metricConduct').textContent=w?'Recupere sua conduta':'Conduta excelente';
    $('#promotionPreview').innerHTML=p.next?`<h3>${esc(p.next.name)}</h3><div class="requirements">${p.requirements.map(x=>`<div class="requirement ${x.ok?'ok':''}"><span>${x.ok?'✓':'○'} ${esc(x.label)}</span><b>${x.ok?'OK':'Pendente'}</b></div>`).join('')}</div>`:`<div class="list-item">Patente máxima alcançada.</div>`;
    const active=C190_Career.goalDefs.filter(g=>!state.career.goals[g.id]?.claimed).slice(0,3);$('#goalPreview').innerHTML=active.length?active.map(g=>{const v=Math.min(g.target,g.metric(state));return `<div class="list-item"><strong>${esc(g.name)}</strong><small>${v}/${g.target}</small><div class="progress"><i style="width:${v/g.target*100}%"></i></div></div>`}).join(''):'<div class="list-item">Todas as metas concluídas.</div>';
    $('#eventTimeline').innerHTML=state.career.events.slice(0,8).map(e=>`<div class="timeline-item"><time>${new Date(e.at).toLocaleString()}</time><div><strong>${esc(e.title)}</strong><div>${esc(e.detail)}</div></div></div>`).join('')||'<div class="list-item">Nenhum evento registrado.</div>';
  }
  function renderDispatch(){const sh=state.dispatch.shift;$('#startShiftBtn').textContent=sh?.active?'Encerrar plantão':'Iniciar plantão';$('#shiftStatus').textContent=sh?.active?`Plantão ativo · ${sh.elapsed}s · resolvidas ${sh.resolved} · falhas ${sh.failed} · abandonadas ${sh.abandoned}`:'Nenhum plantão ativo. Inicie um novo turno para receber três chamadas progressivas.';const waiting=sh?.calls.filter(c=>c.status==='waiting')||[];$('#queueCount').textContent=waiting.length;$('#callQueue').innerHTML=waiting.map(c=>callCard(c,true)).join('')||'<div class="list-item">Fila vazia.</div>';const active=sh?.calls.find(c=>c.id===sh.activeCallId);$('#activeCall').innerHTML=active?activeCall(active):'<div class="list-item">Nenhuma chamada em atendimento.</div>';const paused=sh?.calls.filter(c=>c.status==='paused')||[];$('#pausedCalls').innerHTML=paused.map(c=>callCard(c,false)).join('')||'<div class="list-item">Nenhuma ocorrência pausada.</div>';bindDispatchButtons();}
  function priorityLabel(p){return p===3?'CRÍTICA':p===2?'ALTA':'NORMAL'}
  function callCard(c,waiting){return `<div class="call-card ${c.priority===3?'urgent':waiting?'waiting':''}"><div class="call-meta"><span>${priorityLabel(c.priority)}</span><span>${c.wait}s espera</span></div><strong>${esc(c.type)}</strong><span>${esc(c.location)}</span><button class="action-btn primary" data-answer="${esc(c.id)}">${waiting?'Atender':'Retomar'}</button></div>`;}
  function activeCall(c){return `<div class="call-card urgent"><div class="call-meta"><span>${priorityLabel(c.priority)}</span><span>${c.wait}s espera</span></div><h3>${esc(c.type)}</h3><p>${esc(c.summary)}</p><p><b>Local:</b> ${esc(c.location)}</p><div class="choice-grid">${c.choices.map((ch,i)=>`<button class="choice-btn" data-choice="${i}" data-call="${esc(c.id)}">${esc(ch.text)}</button>`).join('')}</div><button class="action-btn" data-pause="1">Pausar atendimento</button></div>`;}
  function bindDispatchButtons(){$$('[data-answer]').forEach(b=>b.onclick=()=>{C190_Dispatch.answer(state,b.dataset.answer);persist()});$$('[data-choice]').forEach(b=>b.onclick=()=>{const out=C190_Dispatch.choose(state,b.dataset.call,Number(b.dataset.choice));persist();if(out)toast(out.call.status==='resolved'?'Ocorrência resolvida.':'Decisão gerou falha de protocolo.',out.call.status==='resolved'?'success':'danger')});const pause=$('[data-pause]');if(pause)pause.onclick=()=>{C190_Dispatch.pause(state);persist()};}
  function renderCareer(){const idx=C190_Career.rankIndex(state.career.rankId);$('#rankTrack').innerHTML=C190_Career.ranks.map((r,i)=>`<div class="rank-item ${i<idx?'unlocked':''} ${i===idx?'current':''}"><div class="rank-marker">${esc(r.icon)}</div><div><strong>${esc(r.name)}</strong><small>${r.xp} XP · rep. ${r.rep} · ${r.courses} cursos</small></div><span>${i<idx?'Concluída':i===idx?'Atual':'Bloqueada'}</span></div>`).join('');const perf=C190_Career.performance(state);$('#performanceBreakdown').innerHTML=Object.entries({Atendimento:perf.service,Disciplina:perf.discipline,Reputação:perf.reputation,Capacitação:perf.training}).map(([k,v])=>`<div class="list-item"><div class="requirement"><span>${k}</span><b>${v}%</b></div><div class="progress"><i style="width:${v}%"></i></div></div>`).join('');const active=state.career.warnings.filter(w=>!w.expired);$('#warningList').innerHTML=active.length?active.map(w=>`<div class="warning-card"><strong>${esc(w.title)}</strong><p>${esc(w.reason)}</p><small>${w.remainingShifts} plantão(ões) para expirar · reincidências ${w.count}</small></div>`).join(''):'<div class="list-item">Nenhuma advertência ativa.</div>';$('#specializationList').innerHTML=C190_Career.specs.map(sp=>{const ok=sp.requires.every(id=>state.career.completedCourses.includes(id));return `<div class="specialization-card ${state.career.specialization===sp.id?'selected':''}"><div class="card-icon">${sp.icon}</div><h3>${esc(sp.name)}</h3><p>${esc(sp.desc)}</p><small>Requer: ${sp.requires.map(id=>C190_Career.courses.find(c=>c.id===id)?.name).join(' + ')}</small><button class="action-btn primary" data-spec="${sp.id}" ${ok?'':'disabled'}>${state.career.specialization===sp.id?'Selecionada':ok?'Especializar':'Bloqueada'}</button></div>`}).join('');$$('[data-spec]').forEach(b=>b.onclick=()=>{if(C190_Career.selectSpecialization(state,b.dataset.spec)){persist();toast('Especialização atualizada.')}});}
  function renderCourses(){$('#courseGrid').innerHTML=C190_Career.courses.map(c=>{const done=state.career.completedCourses.includes(c.id);const locked=C190_Career.rankIndex(state.career.rankId)<c.minRank;return `<article class="course-card ${locked?'locked':''}"><div class="card-icon">${c.icon}</div><h3>${esc(c.name)}</h3><p>${esc(c.desc)}</p><div class="tag-row"><span class="tag">Custo ${c.cost} XP</span><span class="tag">Patente ${C190_Career.ranks[c.minRank].name}</span></div><button class="action-btn primary" data-course="${c.id}" ${done||locked?'disabled':''}>${done?'Concluído':locked?'Bloqueado':'Matricular'}</button></article>`}).join('');$$('[data-course]').forEach(b=>b.onclick=()=>{const out=C190_Career.completeCourse(state,b.dataset.course);if(out.ok){persist();toast(`Curso concluído: ${out.course.name}`);if(out.promotion)showPromotion(out.promotion)}else toast(out.reason==='xp'?'XP insuficiente para este curso.':'Curso indisponível.','warning')});}
  function renderGoals(){$('#goalsGrid').innerHTML=C190_Career.goalDefs.map(g=>{const rec=state.career.goals[g.id]||{};const v=Math.min(g.target,g.metric(state));return `<article class="goal-card"><h3>${rec.claimed?'✓ ':''}${esc(g.name)}</h3><p>${esc(g.desc)}</p><div class="progress"><i style="width:${v/g.target*100}%"></i></div><strong>${v}/${g.target}</strong><span class="tag">Recompensa ${g.reward.xp} XP${g.reward.rep?` + ${g.reward.rep} reputação`:''}</span></article>`}).join('');}
  function renderAchievements(){$('#achievementGrid').innerHTML=C190_Career.achievements.map(a=>{const on=state.career.achievements.includes(a.id);return `<article class="achievement-card ${on?'':'locked'}"><div class="card-icon">${a.icon}</div><h3>${esc(a.name)}</h3><p>${esc(a.desc)}</p><span class="tag">${on?'Desbloqueada':'Bloqueada'}</span></article>`}).join('');}
  function renderReports(){$('#reportList').innerHTML=state.dispatch.reports.map((r,i)=>`<article class="report-card"><div class="requirement"><h3>Plantão #${state.dispatch.reports.length-i}</h3><b>Nota ${r.grade} · ${r.score}/100</b></div><small>${new Date(r.startedAt).toLocaleString()} · duração ${r.duration}s</small><div class="report-stats"><div class="report-stat"><strong>${r.resolved}</strong><span>Resolvidas</span></div><div class="report-stat"><strong>${r.failed}</strong><span>Falhas</span></div><div class="report-stat"><strong>${r.abandoned}</strong><span>Abandonadas</span></div><div class="report-stat"><strong>${r.calls.length}</strong><span>Chamadas</span></div><div class="report-stat"><strong>${r.grade}</strong><span>Nota</span></div></div></article>`).join('')||'<div class="panel">Nenhum relatório disponível.</div>';}
  function renderSettings(){$('#largeTextToggle').checked=state.settings.largeText;$('#reduceMotionToggle').checked=state.settings.reduceMotion;document.body.classList.toggle('large-text',state.settings.largeText);document.body.classList.toggle('reduce-motion',state.settings.reduceMotion);$('#saveStatus').textContent=`Schema ${state.schema} · versão ${state.version} · atualizado ${new Date(state.updatedAt).toLocaleString()}`;}
  function renderAll(){C190_AntiBreak.safe(()=>{renderDashboard();renderDispatch();renderCareer();renderCourses();renderGoals();renderAchievements();renderReports();renderSettings();},()=>{$('#fatalFallback').hidden=false;});}
  function showPromotion(r){$('#promotionTitle').textContent='Promoção conquistada';$('#promotionText').textContent=`Você foi promovido para ${r.name}. Novos cursos e responsabilidades foram liberados.`;$('#promotionDialog').showModal();}
  function shiftEnded(e){persist();const r=e.detail.report;$('#shiftReportContent').innerHTML=`<div class="report-stats"><div class="report-stat"><strong>${r.grade}</strong><span>Nota</span></div><div class="report-stat"><strong>${r.score}</strong><span>Pontuação</span></div><div class="report-stat"><strong>${r.resolved}</strong><span>Resolvidas</span></div><div class="report-stat"><strong>${r.failed}</strong><span>Falhas</span></div><div class="report-stat"><strong>${r.abandoned}</strong><span>Abandonadas</span></div></div>`;$('#shiftReportDialog').showModal();if(e.detail.promotion)setTimeout(()=>showPromotion(e.detail.promotion),250);}
  function initEvents(){
    $('#careerForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#operatorName').value.trim(),callSign=$('#callSign').value.trim();if(name.length<2||callSign.length<2){toast('Preencha nome e nome de guerra.','warning');return;}state.profile={name,callSign,difficulty:$('#difficulty').value};C190_Career.addEvent(state,'career','Carreira iniciada',`${callSign} assumiu o posto de Operador III.`);persist();toast('Carreira criada com sucesso.');});
    $$('.nav-btn').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$('#menuToggle').onclick=()=>$('#sidebar').classList.toggle('open');$('#languageSelect').value=C190_I18N.language;$('#languageSelect').onchange=e=>{C190_I18N.setLanguage(e.target.value);renderAll()};$('#fullscreenBtn').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{toast('Tela cheia não permitida neste navegador.','warning')}};
    $('#startShiftBtn').onclick=()=>{if(!state.profile){showScreen('dashboard');toast('Crie sua carreira antes do primeiro plantão.','warning');return;}if(state.dispatch.shift?.active){if(confirm('Encerrar o plantão atual? Chamadas pendentes serão registradas como abandonadas.')){C190_Dispatch.forceFinish(state);persist();}}else{C190_Dispatch.startShift(state);persist();toast('Plantão iniciado. A fila receberá três chamadas progressivas.')}};
    $('#largeTextToggle').onchange=e=>{state.settings.largeText=e.target.checked;persist()};$('#reduceMotionToggle').onchange=e=>{state.settings.reduceMotion=e.target.checked;persist()};$('#exportSaveBtn').onclick=()=>C190_Save.exportData(state);$('#importSaveInput').onchange=async e=>{try{state=await C190_Save.importData(e.target.files[0]);renderAll();toast('Save importado com sucesso.')}catch{toast('Arquivo de save inválido.','danger')}};$('#resetSaveBtn').onclick=()=>{if(confirm('Reiniciar toda a carreira? Um backup interno do último save continuará disponível apenas até o próximo salvamento.')){state=C190_Save.reset();C190_Save.save(state);renderAll();showScreen('dashboard');toast('Carreira reiniciada.','warning')}};$('#runDiagnosticsBtn').onclick=()=>{const d=C190_AntiBreak.diagnostics(state);$('#diagnosticOutput').textContent=JSON.stringify(d,null,2);toast(d.ok?'Diagnóstico aprovado.':'Diagnóstico encontrou pendências.',d.ok?'success':'warning')};$('#closePromotionBtn').onclick=()=>$('#promotionDialog').close();$('#closeReportBtn').onclick=()=>$('#shiftReportDialog').close();window.addEventListener('c190:shift-ended',shiftEnded);window.addEventListener('beforeunload',()=>C190_Save.save(state));
  }
  function startTicker(){clearInterval(tickTimer);tickTimer=setInterval(()=>{if(state.dispatch.shift?.active){C190_Dispatch.tick(state);C190_Save.save(state);renderDispatch();}},1000);}
  function init(){C190_I18N.init();$('#languageSelect').value=C190_I18N.language;$('#buildLabel').textContent=`${BUILD} · 13/06/2026 12:59:23 BRT`;initEvents();renderAll();startTicker();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});const diag=C190_AntiBreak.diagnostics(state);if(!diag.ok)console.warn('[C190] diagnostics',diag);}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
