window.C190_Dispatch = (() => {
  const templates=[
    {type:'Ameaça em via pública',priority:3,location:'Rua das Palmeiras',summary:'Solicitante relata ameaça e agressor próximo.',choices:[{text:'Confirmar local, características e risco imediato; acionar viatura prioritária.',q:2,xp:150,rep:2},{text:'Orientar que aguarde e ligar novamente depois.',q:-2,xp:20,rep:-4},{text:'Registrar sem confirmar presença do agressor.',q:-1,xp:45,rep:-2}]},
    {type:'Violência doméstica',priority:3,location:'Jardim Aurora',summary:'Vítima fala baixo e informa que o agressor está no imóvel.',choices:[{text:'Usar perguntas fechadas, confirmar risco, manter linha segura e despachar apoio.',q:2,xp:170,rep:3},{text:'Pedir que confronte o agressor para confirmar a denúncia.',q:-3,xp:0,rep:-6},{text:'Solicitar relato longo antes de qualquer despacho.',q:-1,xp:40,rep:-3}]},
    {type:'Acidente com vítima',priority:3,location:'Av. Central',summary:'Colisão entre dois veículos; uma pessoa não responde.',choices:[{text:'Confirmar segurança da cena, estado da vítima e acionar resgate e trânsito.',q:2,xp:160,rep:2},{text:'Enviar apenas uma viatura sem coletar dados médicos.',q:-1,xp:55,rep:-2},{text:'Orientar remoção imediata da vítima por populares.',q:-2,xp:20,rep:-5}]},
    {type:'Perturbação do sossego',priority:1,location:'Vila Nova',summary:'Som alto recorrente durante a madrugada.',choices:[{text:'Registrar endereço, recorrência e risco; orientar e despachar conforme prioridade.',q:2,xp:95,rep:1},{text:'Encerrar por não ser emergência.',q:-1,xp:30,rep:-1},{text:'Tratar como prioridade máxima, ignorando fila crítica.',q:-1,xp:35,rep:-2}]},
    {type:'Pessoa desaparecida',priority:2,location:'Parque Municipal',summary:'Família procura adolescente desaparecido há algumas horas.',choices:[{text:'Coletar descrição, último local, vulnerabilidades e acionar protocolo de busca.',q:2,xp:135,rep:2},{text:'Mandar aguardar 24 horas antes de registrar.',q:-3,xp:0,rep:-6},{text:'Registrar apenas nome e telefone.',q:-1,xp:40,rep:-2}]},
    {type:'Roubo em andamento',priority:3,location:'Mercado Popular',summary:'Funcionário relata suspeito armado dentro do comércio.',choices:[{text:'Manter solicitante em segurança, obter descrição discreta e acionar resposta imediata.',q:2,xp:180,rep:3},{text:'Pedir que tente impedir a fuga.',q:-3,xp:0,rep:-7},{text:'Colocar em espera sem confirmar risco.',q:-2,xp:20,rep:-4}]},
    {type:'Animal em risco na via',priority:1,location:'Estrada do Norte',summary:'Cão ferido bloqueia parcialmente o trânsito.',choices:[{text:'Avaliar risco viário, sinalização e acionar serviço competente.',q:2,xp:80,rep:1},{text:'Ignorar por não envolver pessoa.',q:-1,xp:25,rep:-1},{text:'Mandar o solicitante retirar o animal sem segurança.',q:-2,xp:15,rep:-3}]},
    {type:'Conflito entre vizinhos',priority:2,location:'Conjunto Esperança',summary:'Discussão intensa com possível dano ao portão.',choices:[{text:'Separar fatos, verificar armas/feridos e despachar conforme risco.',q:2,xp:110,rep:1},{text:'Tomar partido de um dos envolvidos.',q:-2,xp:25,rep:-4},{text:'Classificar como trote sem verificação.',q:-2,xp:15,rep:-3}]}
  ];
  const makeCall=(tpl,i)=>({id:`C${Date.now()}-${i}-${Math.floor(Math.random()*999)}`, ...JSON.parse(JSON.stringify(tpl)), status:'scheduled',wait:0,arrivesAt:i===0?0:i===1?18:38,createdAt:new Date().toISOString(),attempts:0});
  function startShift(state){ if(state.dispatch.shift?.active) return state.dispatch.shift; const chosen=[...templates].sort(()=>Math.random()-.5).slice(0,3).map(makeCall); state.dispatch.shift={active:true,startedAt:new Date().toISOString(),elapsed:0,calls:chosen,activeCallId:null,resolved:0,failed:0,abandoned:0,qualityTotal:0,events:[]}; return state.dispatch.shift; }
  function tick(state){ const sh=state.dispatch.shift;if(!sh?.active)return; sh.elapsed++;
    sh.calls.forEach(c=>{ if(c.status==='scheduled'&&sh.elapsed>=c.arrivesAt){c.status='waiting';sh.events.unshift({at:new Date().toISOString(),text:`Nova chamada: ${c.type}`});} if(c.status==='waiting'){c.wait++;if(c.wait===30)c.priority=Math.min(3,c.priority+1);if(c.wait>=72){c.status='abandoned';sh.abandoned++;window.C190_Career.applyOutcome(state,{quality:-2,xp:0,rep:-4,abandoned:true,reason:`Chamada abandonada após ${c.wait}s: ${c.type}`});}} });
    const done=sh.calls.every(c=>['resolved','failed','abandoned'].includes(c.status)); if(done&&!sh.activeCallId) finishShift(state);
  }
  function answer(state,id){ const sh=state.dispatch.shift;if(!sh?.active)return false; const call=sh.calls.find(c=>c.id===id);if(!call||!['waiting','paused'].includes(call.status))return false; if(sh.activeCallId){const active=sh.calls.find(c=>c.id===sh.activeCallId);if(active){active.status='paused';active.pausedAt=new Date().toISOString();}} call.status='active';call.attempts++;sh.activeCallId=id;return true; }
  function pause(state){const sh=state.dispatch.shift;if(!sh?.activeCallId)return false;const c=sh.calls.find(x=>x.id===sh.activeCallId);if(c)c.status='paused';sh.activeCallId=null;return true;}
  function choose(state,callId,index){const sh=state.dispatch.shift;if(!sh?.active)return null;const c=sh.calls.find(x=>x.id===callId);if(!c||c.status!=='active')return null;const choice=c.choices[index];if(!choice)return null;c.selected=index;c.outcome=choice.q>=1?'resolved':'failed';c.status=c.outcome;sh.activeCallId=null;if(c.outcome==='resolved')sh.resolved++;else sh.failed++;sh.qualityTotal+=choice.q;window.C190_Career.applyOutcome(state,{quality:choice.q,xp:choice.xp,rep:choice.rep,resolved:c.outcome==='resolved',failed:c.outcome==='failed',reason:`${c.type}: ${choice.text}`}); const done=sh.calls.every(x=>['resolved','failed','abandoned'].includes(x.status));if(done)finishShift(state);return {call:c,choice};}
  function finishShift(state){const sh=state.dispatch.shift;if(!sh?.active)return null;sh.active=false;sh.endedAt=new Date().toISOString();const base=sh.resolved*30-sh.failed*18-sh.abandoned*22+sh.qualityTotal*5;const score=Math.max(0,Math.min(100,55+base));const grade=score>=92?'S':score>=80?'A':score>=68?'B':score>=55?'C':'D';const report={id:`R${Date.now()}`,startedAt:sh.startedAt,endedAt:sh.endedAt,duration:sh.elapsed,resolved:sh.resolved,failed:sh.failed,abandoned:sh.abandoned,score,grade,calls:sh.calls.map(c=>({type:c.type,status:c.status,wait:c.wait,priority:c.priority,outcome:c.outcome||c.status}))};const promotion=window.C190_Career.endShift(state,report);window.dispatchEvent(new CustomEvent('c190:shift-ended',{detail:{report,promotion}}));return report;}
  function forceFinish(state){const sh=state.dispatch.shift;if(!sh?.active)return null;sh.calls.forEach(c=>{if(!['resolved','failed','abandoned'].includes(c.status)){c.status='abandoned';sh.abandoned++;window.C190_Career.applyOutcome(state,{quality:-1,xp:0,rep:-2,abandoned:true,reason:`Plantão encerrado com chamada pendente: ${c.type}`});}});sh.activeCallId=null;return finishShift(state);}
  return {templates,startShift,tick,answer,pause,choose,finishShift,forceFinish};
})();
