window.C190_I18N = (() => {
  const dict = {
    'pt-BR': {
      'subtitle.dashboard':'Comando operacional','actions.fullscreen':'Tela cheia','actions.continue':'Continuar','nav.dashboard':'Painel','nav.dispatch':'Plantão','nav.career':'Carreira','nav.training':'Cursos','nav.goals':'Metas','nav.achievements':'Conquistas','nav.reports':'Relatórios','nav.settings':'Configurações',
      'setup.eyebrow':'NOVA CARREIRA','setup.title':'Assuma seu posto na Central 190','setup.desc':'Crie seu perfil operacional. Suas decisões afetam reputação, promoções, advertências e especializações.','setup.name':'Nome do operador','setup.callsign':'Nome de guerra','setup.difficulty':'Dificuldade','setup.start':'Iniciar carreira','difficulty.assisted':'Assistido','difficulty.realistic':'Realista','difficulty.expert':'Especialista',
      'dashboard.careerActive':'CARREIRA ATIVA','career.reputation':'Reputação','career.xp':'Experiência','career.shifts':'Plantões','career.discipline':'Disciplina','dashboard.nextPromotion':'Próxima promoção','dashboard.activeGoals':'Metas ativas','dashboard.recentEvents':'Histórico recente',
      'dispatch.eyebrow':'PLANTÃO CONTÍNUO','dispatch.title':'Central de ocorrências','dispatch.startShift':'Iniciar plantão','dispatch.queue':'Fila viva','dispatch.activeCase':'Atendimento ativo','dispatch.paused':'Ocorrências pausadas',
      'career.eyebrow':'PROGRESSÃO PROFISSIONAL','career.title':'Patentes e reputação','career.rankTrack':'Linha de patentes','career.performance':'Avaliação de desempenho','career.warnings':'Advertências','career.specializations':'Especializações',
      'training.eyebrow':'CAPACITAÇÃO','training.title':'Cursos e certificações','goals.eyebrow':'GESTÃO DE DESEMPENHO','goals.title':'Metas de carreira','achievements.eyebrow':'RECONHECIMENTO','achievements.title':'Conquistas','reports.eyebrow':'HISTÓRICO OPERACIONAL','reports.title':'Relatórios consolidados','reports.shiftComplete':'Plantão concluído',
      'settings.eyebrow':'SISTEMA','settings.title':'Configurações e segurança','settings.interface':'Interface','settings.largeText':'Texto ampliado','settings.reduceMotion':'Reduzir animações','settings.save':'Save e proteção','settings.export':'Exportar save','settings.import':'Importar save','settings.reset':'Reiniciar carreira','settings.diagnostics':'Diagnóstico anti-quebra','settings.runDiagnostics':'Executar diagnóstico'
    },
    en: {
      'subtitle.dashboard':'Operational command','actions.fullscreen':'Fullscreen','actions.continue':'Continue','nav.dashboard':'Dashboard','nav.dispatch':'Shift','nav.career':'Career','nav.training':'Courses','nav.goals':'Goals','nav.achievements':'Achievements','nav.reports':'Reports','nav.settings':'Settings',
      'setup.eyebrow':'NEW CAREER','setup.title':'Take your position at Emergency Dispatch','setup.desc':'Create your operational profile. Your decisions affect reputation, promotions, warnings and specializations.','setup.name':'Operator name','setup.callsign':'Call sign','setup.difficulty':'Difficulty','setup.start':'Start career','difficulty.assisted':'Assisted','difficulty.realistic':'Realistic','difficulty.expert':'Expert',
      'dashboard.careerActive':'ACTIVE CAREER','career.reputation':'Reputation','career.xp':'Experience','career.shifts':'Shifts','career.discipline':'Discipline','dashboard.nextPromotion':'Next promotion','dashboard.activeGoals':'Active goals','dashboard.recentEvents':'Recent history',
      'dispatch.eyebrow':'CONTINUOUS SHIFT','dispatch.title':'Incident center','dispatch.startShift':'Start shift','dispatch.queue':'Live queue','dispatch.activeCase':'Active call','dispatch.paused':'Paused incidents',
      'career.eyebrow':'PROFESSIONAL PROGRESSION','career.title':'Ranks and reputation','career.rankTrack':'Rank path','career.performance':'Performance review','career.warnings':'Warnings','career.specializations':'Specializations',
      'training.eyebrow':'TRAINING','training.title':'Courses and certifications','goals.eyebrow':'PERFORMANCE MANAGEMENT','goals.title':'Career goals','achievements.eyebrow':'RECOGNITION','achievements.title':'Achievements','reports.eyebrow':'OPERATIONAL HISTORY','reports.title':'Consolidated reports','reports.shiftComplete':'Shift completed',
      'settings.eyebrow':'SYSTEM','settings.title':'Settings and safety','settings.interface':'Interface','settings.largeText':'Large text','settings.reduceMotion':'Reduce motion','settings.save':'Save and protection','settings.export':'Export save','settings.import':'Import save','settings.reset':'Reset career','settings.diagnostics':'Anti-break diagnostics','settings.runDiagnostics':'Run diagnostics'
    },
    es: {
      'subtitle.dashboard':'Comando operativo','actions.fullscreen':'Pantalla completa','actions.continue':'Continuar','nav.dashboard':'Panel','nav.dispatch':'Turno','nav.career':'Carrera','nav.training':'Cursos','nav.goals':'Metas','nav.achievements':'Logros','nav.reports':'Informes','nav.settings':'Ajustes',
      'setup.eyebrow':'NUEVA CARRERA','setup.title':'Asume tu puesto en la Central 190','setup.desc':'Crea tu perfil operativo. Tus decisiones afectan reputación, ascensos, advertencias y especializaciones.','setup.name':'Nombre del operador','setup.callsign':'Nombre operativo','setup.difficulty':'Dificultad','setup.start':'Iniciar carrera','difficulty.assisted':'Asistido','difficulty.realistic':'Realista','difficulty.expert':'Especialista',
      'dashboard.careerActive':'CARRERA ACTIVA','career.reputation':'Reputación','career.xp':'Experiencia','career.shifts':'Turnos','career.discipline':'Disciplina','dashboard.nextPromotion':'Próximo ascenso','dashboard.activeGoals':'Metas activas','dashboard.recentEvents':'Historial reciente',
      'dispatch.eyebrow':'TURNO CONTINUO','dispatch.title':'Central de incidencias','dispatch.startShift':'Iniciar turno','dispatch.queue':'Cola activa','dispatch.activeCase':'Atención activa','dispatch.paused':'Incidencias pausadas',
      'career.eyebrow':'PROGRESIÓN PROFESIONAL','career.title':'Rangos y reputación','career.rankTrack':'Línea de rangos','career.performance':'Evaluación de desempeño','career.warnings':'Advertencias','career.specializations':'Especializaciones',
      'training.eyebrow':'CAPACITACIÓN','training.title':'Cursos y certificaciones','goals.eyebrow':'GESTIÓN DEL DESEMPEÑO','goals.title':'Metas de carrera','achievements.eyebrow':'RECONOCIMIENTO','achievements.title':'Logros','reports.eyebrow':'HISTORIAL OPERATIVO','reports.title':'Informes consolidados','reports.shiftComplete':'Turno concluido',
      'settings.eyebrow':'SISTEMA','settings.title':'Ajustes y seguridad','settings.interface':'Interfaz','settings.largeText':'Texto ampliado','settings.reduceMotion':'Reducir animaciones','settings.save':'Guardado y protección','settings.export':'Exportar guardado','settings.import':'Importar guardado','settings.reset':'Reiniciar carrera','settings.diagnostics':'Diagnóstico anti-fallos','settings.runDiagnostics':'Ejecutar diagnóstico'
    }
  };
  let lang = 'pt-BR';
  function t(key){ return dict[lang]?.[key] || dict['pt-BR'][key] || key; }
  function apply(){ document.documentElement.lang=lang; document.querySelectorAll('[data-i18n]').forEach(el=>{ const v=t(el.dataset.i18n); if(el.tagName==='INPUT') el.placeholder=v; else el.textContent=v; }); }
  function setLanguage(next){ lang = dict[next] ? next : 'pt-BR'; localStorage.setItem('central190_language',lang); apply(); window.dispatchEvent(new CustomEvent('c190:language',{detail:lang})); }
  function init(){ lang=localStorage.getItem('central190_language')||'pt-BR'; apply(); }
  return {init,t,setLanguage,get language(){return lang;}};
})();
