export const SUPPORTED_LOCALES = Object.freeze(['pt-BR', 'en-US', 'es-419']);

export const TRANSLATIONS = Object.freeze({
  'pt-BR': {
    meta: { description: 'Central 190 {version} — {module}', phaseModule: '{phase} • {module}' },
    common: {
      city: 'São Paulo', checking: 'Verificando', ok: 'OK', warning: 'ALERTA', back: 'Voltar',
      continue: 'Continuar', career: 'Carreira', sandbox: 'Sandbox', none: 'nenhum', grade: 'Nota',
      operator: 'OPERADOR', system: 'SISTEMA', protocol: 'PROTOCOLO', shift: 'TURNO', live: 'Ao vivo'
    },
    language: { label: 'Idioma', pt: 'PT', en: 'EN', es: 'ES', ptFull: 'Português', enFull: 'Inglês', esFull: 'Espanhol', changed: 'Idioma alterado para português.' },
    accessibility: { largeText: 'Texto maior', highContrast: 'Alto contraste', reduceMotion: 'Reduzir movimento', install: 'Instalar app', installed: 'App instalado', installHint: 'No navegador, use Instalar app ou Adicionar à tela inicial para fullscreen real.', orientation: 'O jogo prioriza celular em retrato; tablet, paisagem e PC continuam jogáveis.', changed: 'Preferência de acessibilidade aplicada.' },
    topbar: { mobileFirst: 'Vale Games • Central operacional', fullscreen: 'Tela cheia', fullscreenAria: 'Alternar tela cheia' },
    home: {
      kicker: 'Atender • Avaliar • Despachar • Proteger', title: 'Central 190', subtitle: 'LINHA DE VIDA',
      description: 'Simulação ultra realista de atendimento policial: informação incompleta, risco dinâmico, protocolo e despacho tático sob pressão.',
      newGame: 'Novo Jogo', continueShift: 'Continuar plantão'
    },
    profile: {
      eyebrow: 'Cadastro inicial', title: 'Monte seu operador', name: 'Nome do operador', namePlaceholder: 'Digite seu nome',
      country: 'País de nascimento', chooseAvatar: 'Escolha seu avatar', mode: 'Modo de jogo', confirm: 'Confirmar operador',
      selectedAvatar: 'Avatar selecionado', selectAvatar: 'Selecionar {name}'
    },
    countries: { BR: 'Brasil', AR: 'Argentina', CL: 'Chile', PT: 'Portugal', US: 'Estados Unidos' },
    modes: { carreira: 'Carreira', sandbox: 'Sandbox' },
    avatars: { operator1: 'Operador 01', operator2: 'Operadora 02', operator3: 'Operador 03', operator4: 'Operador 04', operator5: 'Operadora 05' },
    ranks: { attendant1: 'Atendente I', attendant2: 'Atendente II', attendant3: 'Atendente III', supervisor: 'Supervisor de Plantão' },
    lobby: {
      active: 'Operador ativo', totalXp: 'XP total:', rank: 'Patente', resolved: 'Ocorrências resolvidas', bestTime: 'Melhor tempo',
      baseCity: 'Cidade base', expansion: 'Expansão', dlcReady: 'Pronta para DLC', average: 'Nota média', safeStreak: 'Sequência segura',
      careerProgress: 'Progresso de carreira', awaitingProgress: 'Aguardando evolução', shiftPlan: 'Planejamento do plantão',
      reports: 'Últimos relatórios', noReports: 'Nenhum relatório registrado ainda.', startShift: 'Iniciar Plantão',
      manual: 'Manual de Protocolo', settings: 'Configurações', maxRank: 'Patente máxima da versão atual atingida.',
      xpToRank: '{xp} XP para {rank}.', avatarAlt: 'Avatar do jogador', rankAlt: 'Patente atual'
    },
    shifts: {
      morning: 'Manhã', morningHint: 'trânsito, escola e entrada comercial', morningRadio: 'Rádio: entrada escolar, fluxo intenso e travessias monitoradas.',
      afternoon: 'Tarde', afternoonHint: 'comércio, vias cheias e conflito urbano', afternoonRadio: 'Rádio: comércio ativo, trânsito carregado e apoio distribuído por zona.',
      night: 'Noite', nightHint: 'roubos, bares e risco armado', nightRadio: 'Rádio: prioridade para roubo, bares, violência doméstica e contenção.',
      dawn: 'Madrugada', dawnHint: 'isolamento, violência e resposta crítica', dawnRadio: 'Rádio: efetivo reduzido, baixa visibilidade e ocorrências com isolamento.',
      waitingRadio: 'Rádio: aguardando início do plantão.'
    },
    shift: {
      active: 'Plantão ativo', ongoing: 'Atendimento em andamento', occurrence: 'Ocorrência', highPriority: 'Prioridade alta',
      backLobby: 'Voltar ao lobby', openDispatch: 'Abrir despacho', operationalSummary: 'Resumo operacional',
      realtimeRisk: 'Risco em tempo real', awaitingTriage: 'Aguardando triagem', questionsDone: 'Perguntas essenciais esgotadas. Avalie o despacho.',
      protocolGuidance: 'localização, risco imediato, vítimas e segurança do solicitante devem ser confirmados sempre que a janela operacional permitir.',
      queueStatus: '{shift}. Fila de chamadas simultâneas: {count}. O efetivo deve ser usado com proporcionalidade.',
      registered: 'REGISTRADO: {protocol}.', noUnit: 'não é permitido finalizar sem pelo menos uma unidade ou recurso selecionado.',
      currentQueue: '{radio} Fila atual: {count} ocorrência(s) em triagem.{recovered}', recoveredSuffix: ' Plantão recuperado.',
      radioNewCall: 'Rádio: outra chamada entrou na fila. Priorize coleta mínima e despacho proporcional.',
      radioSupervisor: 'Rádio: supervisão solicita status. Evite manter unidade crítica ociosa sem necessidade.'
    },
    risk: { low: 'Risco controlado', moderate: 'Risco moderado', high: 'Risco alto', critical: 'Risco crítico', criticalAction: 'Risco crítico: decisão imediata recomendada', highAction: 'Risco alto: coletar dados essenciais e despachar', moderateTriage: 'Risco moderado: triagem em andamento' },
    branching: {
      callerState: 'Estado do solicitante', trust: 'Confiança', stress: 'Estresse', clarity: 'Clareza', chooseApproach: 'Postura de comunicação', confirmedIntel: 'Informações confirmadas',
      approaches: { calm: 'Acolhedora', calmShort: 'reduz estresse', direct: 'Objetiva', directShort: 'equilíbrio', urgent: 'Urgente', urgentShort: 'ganha tempo' },
      hints: { calm: 'Acolha, estabilize a respiração e crie confiança. É mais segura com solicitantes em pânico.', direct: 'Faça uma pergunta curta e objetiva. Aumenta a clareza sem elevar muito o estresse.', urgent: 'Use somente diante de risco imediato. Pode acelerar a informação, mas também interromper a ligação.' },
      emotions: { panic: 'Em pânico', agitated: 'Agitado', resistant: 'Resistente', confused: 'Confuso', cooperative: 'Cooperativo', tense: 'Tenso' },
      line: { stable: 'Linha estável', unstable: 'Linha instável' },
      reactions: { cooperative: 'A pessoa consegue organizar a resposta: {reply}', strained: 'Com a voz tensa, a pessoa responde: {reply}', blocked: 'A resposta chega fragmentada: {reply}', interrupted: 'A pessoa fala por cima do operador e a ligação fica momentaneamente interrompida.' },
      approachMeta: '{approach} • qualidade {quality}%', intelRevealed: 'NOVA INFORMAÇÃO CONFIRMADA: {intel}', contradictionRevealed: 'DIVERGÊNCIA IDENTIFICADA: {intel}', interruption: 'LINHA INSTÁVEL: a abordagem elevou o estresse. Reestabeleça confiança e repita a pergunta.',
      intelCount: '{count} confirmada(s)', hiddenIntel: '{count} informação(ões) ainda não confirmada(s)', noIntel: 'Nenhuma informação confirmada além da abertura da chamada.',
      branchQualityTitle: 'Condução da ligação', branchQualityText: 'Qualidade média {quality}%. Confiança {trust}, estresse {stress}, clareza {clarity}. Interrupções: {interruptions}.',
      coverageText: 'Cobertura ponderada: {coverage}% em {asked}/{total} protocolos relevantes.'
    },
    dispatch: { eyebrow: 'Despacho operacional', title: 'Selecionar unidades', finish: 'Finalizar despacho', incidentAlt: 'Ocorrência', patrolAlt: 'Viatura', ambulanceAlt: 'Ambulância', helicopterAlt: 'Helicóptero', center: 'Centro', east: 'Zona Leste', marginal: 'Marginal', patrolEta: 'Viatura • 3 min', samuEta: 'SAMU • 6 min', eagleEta: 'Águia • 4 min' },
    map: {
      traffic: 'Trânsito', blockages: 'Bloqueios', scale: 'Escala', mapAria: 'Mapa tático interativo do despacho', controlsAria: 'Controles do mapa tático', routeModesAria: 'Estratégias de rota da unidade', zoomOut: 'Reduzir zoom', zoomIn: 'Aumentar zoom', centerMap: 'Centralizar mapa', dragHint: 'Arraste o mapa com o dedo ou mouse',
      routePlanner: 'Planejamento de rota', recommended: 'Recomendada', alternative: 'Alternativa', distance: 'Distância', eta: 'Chegada', delay: 'Atraso', routeRisk: 'Risco da rota', blocked: 'bloqueio', selectUnit: 'Selecionar {unit}; chegada estimada em {eta} minutos',
      districts: { north: 'Zona Norte', center: 'Centro', east: 'Zona Leste', west: 'Zona Oeste', south: 'Zona Sul' },
      trafficLevels: { light: 'Leve', moderate: 'Moderado', heavy: 'Intenso', congested: 'Congestionado' },
      routeModes: { fastest: { title: 'Mais rápida', description: 'Prioriza tempo, com maior exposição a trânsito e bloqueios.' }, balanced: { title: 'Equilibrada', description: 'Combina tempo, previsibilidade e segurança operacional.' }, secure: { title: 'Mais segura', description: 'Evita áreas críticas e reduz risco de interceptação.' } },
      blockageTypes: { roadworks: 'Obras na via', collision: 'Colisão bloqueando faixa', closure: 'Via interditada', hazard: 'Perímetro de risco', school: 'Zona escolar congestionada', crowd: 'Aglomeração' },
      unitAlt: { police: 'Viatura policial no mapa', ambulance: 'Ambulância no mapa', helicopter: 'Apoio aéreo no mapa' },
      warningBlockage: 'A rota selecionada cruza {count} bloqueio(s). Considere a alternativa recomendada: {mode}.', warningSafe: 'Rota compatível com o cenário, sem bloqueios críticos detectados.', warningAlternative: 'Rota alternativa selecionada. Estratégia recomendada para esta unidade: {mode}.',
      resultTitle: 'Planejamento tático de rota', resultText: 'Pontuação {score}/30. {recommended}/{total} rota(s) recomendada(s), ETA médio de {eta} min e {blockages} bloqueio(s) atravessado(s).'
    },
    manual: {
      eyebrow: 'Treinamento interno', title: 'Manual de Protocolo 190',
      intro: 'A Academia Operacional oferece treinamento jogável para triagem, segurança do solicitante e despacho proporcional. Use o manual como referência e pratique antes do plantão.',
      item1Title: '1. Localização', item1Text: 'Confirmar bairro, referência, direção de fuga e melhor acesso da viatura.',
      item2Title: '2. Risco imediato', item2Text: 'Identificar arma, agressor presente, disparos, incêndio, combustível ou ameaça contra vítima.',
      item3Title: '3. Vítimas', item3Text: 'Priorizar feridos, crianças, idosos, reféns, pessoa presa ou solicitante sem abrigo.',
      item4Title: '4. Segurança', item4Text: 'Orientar abrigo, manter distância, não perseguir suspeitos e preservar a linha.',
      item5Title: '5. Despacho proporcional', item5Text: 'Enviar recurso suficiente sem sobrecarregar a rede operacional.',
      backLobby: 'Voltar ao lobby', start: 'Iniciar plantão'
    },
    config: {
      eyebrow: 'Configuração e integridade', description: 'Perfil atual: simulador em evolução. Esta build adiciona plantão contínuo, fila viva, chamadas simultâneas, espera, abandono, retomada e relatório consolidado do turno.',
      evaluationTitle: 'Modo de avaliação', evaluationText: 'Rigor alto: tempo, protocolo, proporcionalidade e agravamento contam no resultado.',
      interfaceTitle: 'Interface', interfaceText: 'Interface premium mobile-first com painéis reutilizáveis, hierarquia mais clara e controles críticos sempre acessíveis.',
      contentTitle: 'Conteúdo', contentText: 'Banco validado automaticamente: IDs, unidades, perguntas, eventos, referências e traduções.',
      languageTitle: 'Idioma da operação', languageText: 'A interface, os casos e os relatórios podem ser alternados sem reiniciar o jogo.',
      mobileTitle: 'Mobile, tela cheia e acessibilidade', mobileText: 'Controles locais para leitura, contraste, movimento, instalação PWA e uso confortável no celular.',
      antiBreak: 'Sistema anti-quebra', diagnostics: 'Diagnóstico interno', waitingAudit: 'Aguardando auditoria', runAudit: 'Executar auditoria', export: 'Exportar diagnóstico', restore: 'Restaurar backup',
      dataTitle: 'Proteção de dados', dataText: 'Save v10 protege fila viva, chamadas pausadas, relatórios de turno, operação de campo, frota, mapa, triagem, idioma, checksum, backup e recuperação por até 24 horas.', reset: 'Resetar carreira'
    },
    result: {
      eyebrow: 'Relatório pós-despacho', mission: 'Resultado da missão', technical: 'Relatório técnico de desempenho', returnShift: 'Voltar ao plantão', endShift: 'Encerrar plantão', next: 'Próxima ocorrência', returnLobby: 'Voltar ao lobby', resultAlt: 'Resultado', hit: 'Acerto', error: 'Erro',
      exemplary: 'Atuação profissional exemplar', safe: 'Ocorrência conduzida com segurança', caveats: 'Resolvida com ressalvas operacionais', criticalFailures: 'Falhas críticas no protocolo',
      dispatchOk: 'Despacho compatível com risco', dispatchLow: 'Despacho subdimensionado', requiredSelected: 'Exigido: {required}. Selecionado: {selected}.',
      criticalData: 'Coleta de dados críticos', criticalDataText: '{asked}/{total} protocolos relevantes confirmados antes do despacho. {coverageText}',
      responseTime: 'Tempo de resposta operacional', responseTimeText: 'Despacho em {time}. Janela ideal: até {limit}.',
      proportional: 'Uso proporcional de recursos', excessive: 'Recurso possivelmente excessivo: {extra}.', noOverload: 'Não houve sobrecarga desnecessária de recursos.',
      escalation: 'Controle de agravamento', escalationText: 'Índice final de risco: {risk}/100.',
      queue: 'Gestão de fila do plantão', queueText: 'Turno {shift}; {count} chamada(s) ainda aguardando triagem.', callManagement: 'Condução da ligação'
    },
    diagnostics: {
      systemOk: 'Sistema OK', alerts: '{count} alerta(s)', success: 'Todos os controles estruturais passaram.', failures: 'Diagnóstico concluído com {count} alerta(s).',
      auditOk: 'Auditoria interna concluída sem falhas.', auditWarning: 'Auditoria interna encontrou alertas.',
      labels: { build: 'Identificação da build', content: 'Integridade do conteúdo', locales: 'Integridade dos idiomas', dom: 'Componentes essenciais', storage: 'Armazenamento local', backup: 'Backup de carreira', viewport: 'Viewport', serviceWorker: 'PWA / Service Worker', secureContext: 'Contexto seguro' },
      details: { absent: 'ausente', incidentsValidated: '{count} ocorrências validadas', errors: '{count} erro(s)', localesReady: 'PT-BR, EN-US e ES-419 completos', localeErrors: '{count} tradução(ões) ausente(s)', missing: 'Ausentes: {items}', componentsFound: '{count} componentes encontrados', storageOps: 'leitura, escrita e remoção testadas', backupAvailable: 'backup disponível', backupLater: 'será criado após o primeiro salvamento', compatible: 'compatível', unavailable: 'indisponível', localFile: 'arquivo local' }
    },
    notifications: {
      missingName: 'Digite o nome do operador.', fullscreenDenied: 'O navegador exige instalação como app ou não permite tela cheia neste momento.',
      saveFailure: 'Não foi possível salvar. O jogo continua ativo; exporte o diagnóstico.', resetConfirm: 'Resetar carreira, backups e recuperação local deste navegador?',
      careerRemoved: 'Carreira local removida.', sessionSafe: 'Sessão estabilizada. Seus dados de carreira foram preservados.', contentBlocked: 'Conteúdo bloqueado pela validação de segurança. Consulte Configurações.', shiftBlocked: 'O plantão foi bloqueado porque o conteúdo ou os idiomas não passaram na validação.', shiftRecovered: 'Plantão recuperado com segurança.'
    },
    save: { invalidSave: 'Tentativa de salvar dados inválidos.', backupAutoRestored: 'Save principal inválido; backup restaurado automaticamente.', legacyMigrated: 'Save legado {key} migrado para v0.18.0.', noBackup: 'Nenhum backup íntegro disponível.', backupRestored: 'Backup restaurado com sucesso.', backupInvalid: 'Backup inválido: {reason}' },
    recovery: { eyebrow: 'Proteção anti-quebra ativada', title: 'O jogo encontrou uma falha inesperada', text: 'Seu progresso foi preservado sempre que possível. Retorne a uma tela segura ou recarregue a aplicação.', code: 'Erro de execução', safe: 'Retornar com segurança', reload: 'Recarregar' },
    build: { phase: 'Fase 12 de 20', module: 'Plantão contínuo, fila viva e relatório consolidado' }
  },
  'en-US': {
    meta: { description: 'Central 190 {version} — {module}', phaseModule: '{phase} • {module}' },
    common: { city: 'São Paulo', checking: 'Checking', ok: 'OK', warning: 'WARNING', back: 'Back', continue: 'Continue', career: 'Career', sandbox: 'Sandbox', none: 'none', grade: 'Grade', operator: 'OPERATOR', system: 'SYSTEM', protocol: 'PROTOCOL', shift: 'SHIFT', live: 'Live' },
    language: { label: 'Language', pt: 'PT', en: 'EN', es: 'ES', ptFull: 'Portuguese', enFull: 'English', esFull: 'Spanish', changed: 'Language changed to English.' },
    accessibility: { largeText: 'Larger text', highContrast: 'High contrast', reduceMotion: 'Reduce motion', install: 'Install app', installed: 'App installed', installHint: 'Use Install app or Add to home screen for true fullscreen mode.', orientation: 'The game prioritizes portrait phones; tablet, landscape and PC remain playable.', changed: 'Accessibility preference applied.' },
    topbar: { mobileFirst: 'Vale Games • Operations center', fullscreen: 'Fullscreen', fullscreenAria: 'Toggle fullscreen' },
    home: { kicker: 'Answer • Assess • Dispatch • Protect', title: 'Central 190', subtitle: 'LIFELINE', description: 'A realistic emergency call simulation with incomplete information, dynamic risk, protocol and tactical dispatch under pressure.', newGame: 'New Game', continueShift: 'Continue shift' },
    profile: { eyebrow: 'Initial registration', title: 'Create your operator', name: 'Operator name', namePlaceholder: 'Enter your name', country: 'Country of birth', chooseAvatar: 'Choose your avatar', mode: 'Game mode', confirm: 'Confirm operator', selectedAvatar: 'Selected avatar', selectAvatar: 'Select {name}' },
    countries: { BR: 'Brazil', AR: 'Argentina', CL: 'Chile', PT: 'Portugal', US: 'United States' },
    modes: { carreira: 'Career', sandbox: 'Sandbox' },
    avatars: { operator1: 'Operator 01', operator2: 'Operator 02', operator3: 'Operator 03', operator4: 'Operator 04', operator5: 'Operator 05' },
    ranks: { attendant1: 'Call Taker I', attendant2: 'Call Taker II', attendant3: 'Call Taker III', supervisor: 'Shift Supervisor' },
    lobby: { active: 'Active operator', totalXp: 'Total XP:', rank: 'Rank', resolved: 'Incidents resolved', bestTime: 'Best time', baseCity: 'Base city', expansion: 'Expansion', dlcReady: 'DLC-ready', average: 'Average grade', safeStreak: 'Safe streak', careerProgress: 'Career progress', awaitingProgress: 'Awaiting progress', shiftPlan: 'Shift planning', reports: 'Latest reports', noReports: 'No reports recorded yet.', startShift: 'Start Shift', manual: 'Protocol Manual', settings: 'Settings', maxRank: 'Maximum rank for the current version reached.', xpToRank: '{xp} XP to {rank}.', avatarAlt: 'Player avatar', rankAlt: 'Current rank' },
    shifts: { morning: 'Morning', morningHint: 'traffic, schools and business opening', morningRadio: 'Radio: school arrival, heavy traffic and monitored crossings.', afternoon: 'Afternoon', afternoonHint: 'commerce, busy roads and urban conflict', afternoonRadio: 'Radio: active commerce, congested traffic and support distributed by zone.', night: 'Night', nightHint: 'robberies, bars and armed risk', nightRadio: 'Radio: priority for robbery, bars, domestic violence and containment.', dawn: 'Late night', dawnHint: 'isolation, violence and critical response', dawnRadio: 'Radio: reduced staffing, low visibility and isolated incidents.', waitingRadio: 'Radio: waiting for the shift to start.' },
    shift: { active: 'Active shift', ongoing: 'Call in progress', occurrence: 'Incident', highPriority: 'High priority', backLobby: 'Back to lobby', openDispatch: 'Open dispatch', operationalSummary: 'Operational summary', realtimeRisk: 'Real-time risk', awaitingTriage: 'Awaiting triage', questionsDone: 'Essential questions exhausted. Assess the dispatch.', protocolGuidance: 'location, immediate risk, victims and caller safety must be confirmed whenever the operational window allows.', queueStatus: '{shift}. Simultaneous call queue: {count}. Resources must be used proportionally.', registered: 'RECORDED: {protocol}.', noUnit: 'you cannot complete the dispatch without selecting at least one unit or resource.', currentQueue: '{radio} Current queue: {count} incident(s) in triage.{recovered}', recoveredSuffix: ' Shift recovered.', radioNewCall: 'Radio: another call entered the queue. Prioritize minimum data collection and proportional dispatch.', radioSupervisor: 'Radio: supervision requests a status update. Do not keep critical resources idle without need.' },
    risk: { low: 'Risk controlled', moderate: 'Moderate risk', high: 'High risk', critical: 'Critical risk', criticalAction: 'Critical risk: immediate decision recommended', highAction: 'High risk: collect essential data and dispatch', moderateTriage: 'Moderate risk: triage in progress' },
    branching: { callerState: 'Caller state', trust: 'Trust', stress: 'Stress', clarity: 'Clarity', chooseApproach: 'Communication approach', confirmedIntel: 'Confirmed intelligence', approaches: { calm: 'Supportive', calmShort: 'reduces stress', direct: 'Direct', directShort: 'balanced', urgent: 'Urgent', urgentShort: 'saves time' }, hints: { calm: 'Stabilize breathing and build trust. This is safer with panicked callers.', direct: 'Ask a short, objective question. It improves clarity without sharply increasing stress.', urgent: 'Use only for immediate danger. It may speed up information but can also disrupt the call.' }, emotions: { panic: 'Panicked', agitated: 'Agitated', resistant: 'Resistant', confused: 'Confused', cooperative: 'Cooperative', tense: 'Tense' }, line: { stable: 'Stable line', unstable: 'Unstable line' }, reactions: { cooperative: 'The caller organizes the answer: {reply}', strained: 'In a tense voice, the caller answers: {reply}', blocked: 'Only a fragmented response is understandable: {reply}', interrupted: 'The caller talks over the operator and the line is briefly disrupted.' }, approachMeta: '{approach} • quality {quality}%', intelRevealed: 'NEW CONFIRMED INFORMATION: {intel}', contradictionRevealed: 'CONFLICTING INFORMATION IDENTIFIED: {intel}', interruption: 'UNSTABLE LINE: the approach raised stress. Rebuild trust and repeat the question.', intelCount: '{count} confirmed', hiddenIntel: '{count} item(s) still unconfirmed', noIntel: 'No information has been confirmed beyond the opening statement.', branchQualityTitle: 'Call management', branchQualityText: 'Average quality {quality}%. Trust {trust}, stress {stress}, clarity {clarity}. Interruptions: {interruptions}.', coverageText: 'Weighted coverage: {coverage}% across {asked}/{total} relevant protocols.' },
    dispatch: { eyebrow: 'Operational dispatch', title: 'Select units', finish: 'Complete dispatch', incidentAlt: 'Incident', patrolAlt: 'Patrol unit', ambulanceAlt: 'Ambulance', helicopterAlt: 'Helicopter', center: 'Downtown', east: 'East Zone', marginal: 'Expressway', patrolEta: 'Patrol • 3 min', samuEta: 'EMS • 6 min', eagleEta: 'Air • 4 min' },
    map: {
      traffic: 'Traffic', blockages: 'Blockages', scale: 'Scale', mapAria: 'Interactive tactical dispatch map', controlsAria: 'Tactical map controls', routeModesAria: 'Unit route strategies', zoomOut: 'Zoom out', zoomIn: 'Zoom in', centerMap: 'Center map', dragHint: 'Drag the map with touch or mouse',
      routePlanner: 'Route planning', recommended: 'Recommended', alternative: 'Alternative', distance: 'Distance', eta: 'Arrival', delay: 'Delay', routeRisk: 'Route risk', blocked: 'blocked', selectUnit: 'Select {unit}; estimated arrival in {eta} minutes',
      districts: { north: 'North Zone', center: 'Downtown', east: 'East Zone', west: 'West Zone', south: 'South Zone' },
      trafficLevels: { light: 'Light', moderate: 'Moderate', heavy: 'Heavy', congested: 'Congested' },
      routeModes: { fastest: { title: 'Fastest', description: 'Prioritizes time with greater exposure to traffic and blockages.' }, balanced: { title: 'Balanced', description: 'Combines time, predictability and operational safety.' }, secure: { title: 'Safest', description: 'Avoids critical areas and reduces interception risk.' } },
      blockageTypes: { roadworks: 'Roadworks', collision: 'Collision blocking a lane', closure: 'Road closure', hazard: 'Hazard perimeter', school: 'Congested school zone', crowd: 'Crowd' },
      unitAlt: { police: 'Police unit on the map', ambulance: 'Ambulance on the map', helicopter: 'Air support on the map' },
      warningBlockage: 'The selected route crosses {count} blockage(s). Consider the recommended alternative: {mode}.', warningSafe: 'Route matches the scenario with no critical blockages detected.', warningAlternative: 'Alternative route selected. Recommended strategy for this unit: {mode}.',
      resultTitle: 'Tactical route planning', resultText: 'Score {score}/30. {recommended}/{total} recommended route(s), average ETA {eta} min and {blockages} crossed blockage(s).'
    },
    manual: { eyebrow: 'Internal training', title: 'Emergency Protocol Manual', intro: 'The Operations Academy provides playable training in triage, caller safety and proportional dispatch. Use the manual as reference and practice before a shift.', item1Title: '1. Location', item1Text: 'Confirm district, landmark, escape direction and best unit access.', item2Title: '2. Immediate risk', item2Text: 'Identify weapons, an active aggressor, shots, fire, fuel or direct threats.', item3Title: '3. Victims', item3Text: 'Prioritize injured people, children, older adults, hostages, trapped people or callers without shelter.', item4Title: '4. Safety', item4Text: 'Direct the caller to shelter, keep distance, avoid pursuit and preserve the line.', item5Title: '5. Proportional dispatch', item5Text: 'Send sufficient resources without overloading the operational network.', backLobby: 'Back to lobby', start: 'Start shift' },
    config: { eyebrow: 'Configuration and integrity', description: 'Current profile: evolving simulator. This build adds a continuous shift, live queue, simultaneous calls, waiting, abandonment, resumption and a consolidated shift report.', evaluationTitle: 'Evaluation mode', evaluationText: 'High rigor: time, protocol, proportionality and escalation affect the result.', interfaceTitle: 'Interface', interfaceText: 'Premium mobile-first interface with reusable panels, clearer hierarchy and critical controls always accessible.', contentTitle: 'Content', contentText: 'Database validated automatically: IDs, units, questions, events, references and translations.', languageTitle: 'Operation language', languageText: 'Interface, cases and reports can switch without restarting the game.', mobileTitle: 'Mobile, fullscreen and accessibility', mobileText: 'Local controls for reading, contrast, motion, PWA installation and comfortable phone use.', antiBreak: 'Anti-break system', diagnostics: 'Internal diagnostics', waitingAudit: 'Awaiting audit', runAudit: 'Run audit', export: 'Export diagnostics', restore: 'Restore backup', dataTitle: 'Data protection', dataText: 'Save v10 protects the live queue, paused calls, shift reports, field operations, fleet, map, triage, language, checksum, backups and recovery for up to 24 hours.', reset: 'Reset career' },
    result: { eyebrow: 'Post-dispatch report', mission: 'Mission result', technical: 'Technical performance report', returnShift: 'Return to shift', endShift: 'End shift', next: 'Next incident', returnLobby: 'Back to lobby', resultAlt: 'Result', hit: 'Correct', error: 'Error', exemplary: 'Exemplary professional response', safe: 'Incident handled safely', caveats: 'Resolved with operational caveats', criticalFailures: 'Critical protocol failures', dispatchOk: 'Dispatch matches the risk', dispatchLow: 'Dispatch is under-resourced', requiredSelected: 'Required: {required}. Selected: {selected}.', criticalData: 'Critical data collection', criticalDataText: '{asked}/{total} relevant protocols confirmed before dispatch. {coverageText}', responseTime: 'Operational response time', responseTimeText: 'Dispatched in {time}. Ideal window: up to {limit}.', proportional: 'Proportionate resource use', excessive: 'Possibly excessive resource: {extra}.', noOverload: 'No unnecessary resource overload.', escalation: 'Escalation control', escalationText: 'Final risk index: {risk}/100.', queue: 'Shift queue management', queueText: '{shift} shift; {count} call(s) still waiting for triage.', callManagement: 'Call management' },
    diagnostics: { systemOk: 'System OK', alerts: '{count} warning(s)', success: 'All structural controls passed.', failures: 'Diagnostics completed with {count} warning(s).', auditOk: 'Internal audit completed without failures.', auditWarning: 'Internal audit found warnings.', labels: { build: 'Build identification', content: 'Content integrity', locales: 'Language integrity', dom: 'Essential components', storage: 'Local storage', backup: 'Career backup', viewport: 'Viewport', serviceWorker: 'PWA / Service Worker', secureContext: 'Secure context' }, details: { absent: 'missing', incidentsValidated: '{count} incidents validated', errors: '{count} error(s)', localesReady: 'PT-BR, EN-US and ES-419 complete', localeErrors: '{count} missing translation(s)', missing: 'Missing: {items}', componentsFound: '{count} components found', storageOps: 'read, write and removal tested', backupAvailable: 'backup available', backupLater: 'created after the first save', compatible: 'compatible', unavailable: 'unavailable', localFile: 'local file' } },
    notifications: { missingName: 'Enter the operator name.', fullscreenDenied: 'The browser requires app installation or does not allow fullscreen right now.', saveFailure: 'Could not save. The game remains active; export diagnostics.', resetConfirm: 'Reset career, backups and local recovery in this browser?', careerRemoved: 'Local career removed.', sessionSafe: 'Session stabilized. Your career data was preserved.', contentBlocked: 'Content blocked by safety validation. Open Settings.', shiftBlocked: 'The shift was blocked because content or language validation failed.', shiftRecovered: 'Shift recovered safely.' },
    save: { invalidSave: 'Attempted to save invalid data.', backupAutoRestored: 'Primary save was invalid; backup restored automatically.', legacyMigrated: 'Legacy save {key} migrated to v0.18.0.', noBackup: 'No valid backup is available.', backupRestored: 'Backup restored successfully.', backupInvalid: 'Invalid backup: {reason}' },
    recovery: { eyebrow: 'Anti-break protection activated', title: 'The game found an unexpected failure', text: 'Your progress was preserved whenever possible. Return to a safe screen or reload the application.', code: 'Runtime error', safe: 'Return safely', reload: 'Reload' },
    build: { phase: 'Phase 12 of 20', module: 'Continuous shift, live queue and consolidated report' }
  },
  'es-419': {
    meta: { description: 'Central 190 {version} — {module}', phaseModule: '{phase} • {module}' },
    common: { city: 'São Paulo', checking: 'Verificando', ok: 'OK', warning: 'ALERTA', back: 'Volver', continue: 'Continuar', career: 'Carrera', sandbox: 'Sandbox', none: 'ninguno', grade: 'Nota', operator: 'OPERADOR', system: 'SISTEMA', protocol: 'PROTOCOLO', shift: 'TURNO', live: 'En vivo' },
    language: { label: 'Idioma', pt: 'PT', en: 'EN', es: 'ES', ptFull: 'Portugués', enFull: 'Inglés', esFull: 'Español', changed: 'Idioma cambiado a español.' },
    accessibility: { largeText: 'Texto mayor', highContrast: 'Alto contraste', reduceMotion: 'Reducir movimiento', install: 'Instalar app', installed: 'App instalada', installHint: 'Usa Instalar app o Agregar a pantalla de inicio para pantalla completa real.', orientation: 'El juego prioriza celular en vertical; tableta, horizontal y PC siguen jugables.', changed: 'Preferencia de accesibilidad aplicada.' },
    topbar: { mobileFirst: 'Vale Games • Central operativa', fullscreen: 'Pantalla completa', fullscreenAria: 'Alternar pantalla completa' },
    home: { kicker: 'Atender • Evaluar • Despachar • Proteger', title: 'Central 190', subtitle: 'LÍNEA DE VIDA', description: 'Simulación realista de llamadas de emergencia con información incompleta, riesgo dinámico, protocolo y despacho táctico bajo presión.', newGame: 'Nuevo juego', continueShift: 'Continuar turno' },
    profile: { eyebrow: 'Registro inicial', title: 'Crea tu operador', name: 'Nombre del operador', namePlaceholder: 'Escribe tu nombre', country: 'País de nacimiento', chooseAvatar: 'Elige tu avatar', mode: 'Modo de juego', confirm: 'Confirmar operador', selectedAvatar: 'Avatar seleccionado', selectAvatar: 'Seleccionar {name}' },
    countries: { BR: 'Brasil', AR: 'Argentina', CL: 'Chile', PT: 'Portugal', US: 'Estados Unidos' },
    modes: { carreira: 'Carrera', sandbox: 'Sandbox' },
    avatars: { operator1: 'Operador 01', operator2: 'Operadora 02', operator3: 'Operador 03', operator4: 'Operador 04', operator5: 'Operadora 05' },
    ranks: { attendant1: 'Operador I', attendant2: 'Operador II', attendant3: 'Operador III', supervisor: 'Supervisor de turno' },
    lobby: { active: 'Operador activo', totalXp: 'XP total:', rank: 'Rango', resolved: 'Incidentes resueltos', bestTime: 'Mejor tiempo', baseCity: 'Ciudad base', expansion: 'Expansión', dlcReady: 'Lista para DLC', average: 'Nota media', safeStreak: 'Racha segura', careerProgress: 'Progreso de carrera', awaitingProgress: 'Esperando progreso', shiftPlan: 'Planificación del turno', reports: 'Últimos informes', noReports: 'Aún no hay informes registrados.', startShift: 'Iniciar turno', manual: 'Manual de protocolo', settings: 'Configuración', maxRank: 'Rango máximo de la versión actual alcanzado.', xpToRank: '{xp} XP para {rank}.', avatarAlt: 'Avatar del jugador', rankAlt: 'Rango actual' },
    shifts: { morning: 'Mañana', morningHint: 'tránsito, escuelas y apertura comercial', morningRadio: 'Radio: entrada escolar, tráfico intenso y cruces vigilados.', afternoon: 'Tarde', afternoonHint: 'comercio, vías llenas y conflicto urbano', afternoonRadio: 'Radio: comercio activo, tráfico cargado y apoyo distribuido por zona.', night: 'Noche', nightHint: 'robos, bares y riesgo armado', nightRadio: 'Radio: prioridad para robos, bares, violencia doméstica y contención.', dawn: 'Madrugada', dawnHint: 'aislamiento, violencia y respuesta crítica', dawnRadio: 'Radio: personal reducido, baja visibilidad e incidentes aislados.', waitingRadio: 'Radio: esperando el inicio del turno.' },
    shift: { active: 'Turno activo', ongoing: 'Llamada en curso', occurrence: 'Incidente', highPriority: 'Prioridad alta', backLobby: 'Volver al lobby', openDispatch: 'Abrir despacho', operationalSummary: 'Resumen operativo', realtimeRisk: 'Riesgo en tiempo real', awaitingTriage: 'Esperando triaje', questionsDone: 'Se agotaron las preguntas esenciales. Evalúa el despacho.', protocolGuidance: 'la ubicación, el riesgo inmediato, las víctimas y la seguridad del solicitante deben confirmarse siempre que la ventana operativa lo permita.', queueStatus: '{shift}. Cola de llamadas simultáneas: {count}. Los recursos deben usarse proporcionalmente.', registered: 'REGISTRADO: {protocol}.', noUnit: 'no se puede finalizar sin seleccionar al menos una unidad o recurso.', currentQueue: '{radio} Cola actual: {count} incidente(s) en triaje.{recovered}', recoveredSuffix: ' Turno recuperado.', radioNewCall: 'Radio: entró otra llamada en la cola. Prioriza la recolección mínima y el despacho proporcional.', radioSupervisor: 'Radio: supervisión solicita estado. Evita mantener recursos críticos inactivos sin necesidad.' },
    risk: { low: 'Riesgo controlado', moderate: 'Riesgo moderado', high: 'Riesgo alto', critical: 'Riesgo crítico', criticalAction: 'Riesgo crítico: se recomienda una decisión inmediata', highAction: 'Riesgo alto: reúne datos esenciales y despacha', moderateTriage: 'Riesgo moderado: triaje en curso' },
    branching: { callerState: 'Estado del solicitante', trust: 'Confianza', stress: 'Estrés', clarity: 'Claridad', chooseApproach: 'Enfoque de comunicación', confirmedIntel: 'Información confirmada', approaches: { calm: 'Contenedora', calmShort: 'reduce estrés', direct: 'Objetiva', directShort: 'equilibrio', urgent: 'Urgente', urgentShort: 'ahorra tiempo' }, hints: { calm: 'Estabiliza la respiración y crea confianza. Es más segura con personas en pánico.', direct: 'Haz una pregunta corta y objetiva. Mejora la claridad sin aumentar demasiado el estrés.', urgent: 'Úsala solo ante peligro inmediato. Puede acelerar la información, pero también interrumpir la llamada.' }, emotions: { panic: 'En pánico', agitated: 'Agitado', resistant: 'Resistente', confused: 'Confuso', cooperative: 'Cooperativo', tense: 'Tenso' }, line: { stable: 'Línea estable', unstable: 'Línea inestable' }, reactions: { cooperative: 'La persona logra ordenar la respuesta: {reply}', strained: 'Con voz tensa, la persona responde: {reply}', blocked: 'La respuesta llega fragmentada: {reply}', interrupted: 'La persona habla encima del operador y la línea se interrumpe momentáneamente.' }, approachMeta: '{approach} • calidad {quality}%', intelRevealed: 'NUEVA INFORMACIÓN CONFIRMADA: {intel}', contradictionRevealed: 'DIVERGENCIA IDENTIFICADA: {intel}', interruption: 'LÍNEA INESTABLE: el enfoque elevó el estrés. Recupera la confianza y repite la pregunta.', intelCount: '{count} confirmada(s)', hiddenIntel: '{count} dato(s) aún sin confirmar', noIntel: 'No se confirmó información adicional a la apertura de la llamada.', branchQualityTitle: 'Conducción de la llamada', branchQualityText: 'Calidad media {quality}%. Confianza {trust}, estrés {stress}, claridad {clarity}. Interrupciones: {interruptions}.', coverageText: 'Cobertura ponderada: {coverage}% en {asked}/{total} protocolos relevantes.' },
    dispatch: { eyebrow: 'Despacho operativo', title: 'Seleccionar unidades', finish: 'Finalizar despacho', incidentAlt: 'Incidente', patrolAlt: 'Patrulla', ambulanceAlt: 'Ambulancia', helicopterAlt: 'Helicóptero', center: 'Centro', east: 'Zona Este', marginal: 'Vía rápida', patrolEta: 'Patrulla • 3 min', samuEta: 'SAMU • 6 min', eagleEta: 'Aéreo • 4 min' },
    map: {
      traffic: 'Tránsito', blockages: 'Bloqueos', scale: 'Escala', mapAria: 'Mapa táctico interactivo del despacho', controlsAria: 'Controles del mapa táctico', routeModesAria: 'Estrategias de ruta de la unidad', zoomOut: 'Alejar mapa', zoomIn: 'Acercar mapa', centerMap: 'Centrar mapa', dragHint: 'Arrastra el mapa con el dedo o el mouse',
      routePlanner: 'Planificación de ruta', recommended: 'Recomendada', alternative: 'Alternativa', distance: 'Distancia', eta: 'Llegada', delay: 'Demora', routeRisk: 'Riesgo de ruta', blocked: 'bloqueo', selectUnit: 'Seleccionar {unit}; llegada estimada en {eta} minutos',
      districts: { north: 'Zona Norte', center: 'Centro', east: 'Zona Este', west: 'Zona Oeste', south: 'Zona Sur' },
      trafficLevels: { light: 'Ligero', moderate: 'Moderado', heavy: 'Intenso', congested: 'Congestionado' },
      routeModes: { fastest: { title: 'Más rápida', description: 'Prioriza el tiempo con mayor exposición al tránsito y bloqueos.' }, balanced: { title: 'Equilibrada', description: 'Combina tiempo, previsibilidad y seguridad operativa.' }, secure: { title: 'Más segura', description: 'Evita áreas críticas y reduce el riesgo de interceptación.' } },
      blockageTypes: { roadworks: 'Obras en la vía', collision: 'Colisión bloqueando un carril', closure: 'Vía cerrada', hazard: 'Perímetro de riesgo', school: 'Zona escolar congestionada', crowd: 'Aglomeración' },
      unitAlt: { police: 'Patrulla en el mapa', ambulance: 'Ambulancia en el mapa', helicopter: 'Apoyo aéreo en el mapa' },
      warningBlockage: 'La ruta seleccionada cruza {count} bloqueo(s). Considera la alternativa recomendada: {mode}.', warningSafe: 'Ruta compatible con el escenario, sin bloqueos críticos detectados.', warningAlternative: 'Ruta alternativa seleccionada. Estrategia recomendada para esta unidad: {mode}.',
      resultTitle: 'Planificación táctica de ruta', resultText: 'Puntuación {score}/30. {recommended}/{total} ruta(s) recomendada(s), ETA promedio de {eta} min y {blockages} bloqueo(s) atravesado(s).'
    },
    manual: { eyebrow: 'Entrenamiento interno', title: 'Manual de protocolo de emergencias', intro: 'La Academia Operativa ofrece entrenamiento jugable de triaje, seguridad del solicitante y despacho proporcional. Usa el manual como referencia y practica antes del turno.', item1Title: '1. Ubicación', item1Text: 'Confirmar barrio, referencia, dirección de fuga y mejor acceso de la unidad.', item2Title: '2. Riesgo inmediato', item2Text: 'Identificar armas, agresor presente, disparos, incendio, combustible o amenazas directas.', item3Title: '3. Víctimas', item3Text: 'Priorizar heridos, niños, adultos mayores, rehenes, personas atrapadas o solicitantes sin refugio.', item4Title: '4. Seguridad', item4Text: 'Indicar refugio, mantener distancia, no perseguir sospechosos y conservar la línea.', item5Title: '5. Despacho proporcional', item5Text: 'Enviar recursos suficientes sin sobrecargar la red operativa.', backLobby: 'Volver al lobby', start: 'Iniciar turno' },
    config: { eyebrow: 'Configuración e integridad', description: 'Perfil actual: simulador en evolución. Esta build incorpora turno continuo, cola viva, llamadas simultáneas, espera, abandono, reanudación e informe consolidado.', evaluationTitle: 'Modo de evaluación', evaluationText: 'Rigor alto: tiempo, protocolo, proporcionalidad y agravamiento cuentan en el resultado.', interfaceTitle: 'Interfaz', interfaceText: 'Interfaz premium mobile-first con paneles reutilizables, jerarquía más clara y controles críticos siempre accesibles.', contentTitle: 'Contenido', contentText: 'Base validada automáticamente: IDs, unidades, preguntas, eventos, referencias y traducciones.', languageTitle: 'Idioma de operación', languageText: 'La interfaz, los casos y los informes pueden cambiarse sin reiniciar el juego.', mobileTitle: 'Mobile, pantalla completa y accesibilidad', mobileText: 'Controles locales para lectura, contraste, movimiento, instalación PWA y uso cómodo en celular.', antiBreak: 'Sistema antirotura', diagnostics: 'Diagnóstico interno', waitingAudit: 'Esperando auditoría', runAudit: 'Ejecutar auditoría', export: 'Exportar diagnóstico', restore: 'Restaurar copia', dataTitle: 'Protección de datos', dataText: 'Save v10 protege cola viva, llamadas pausadas, informes de turno, operación de campo, flota, mapa, triaje, idioma, checksum, copias y recuperación hasta por 24 horas.', reset: 'Reiniciar carrera' },
    result: { eyebrow: 'Informe posterior al despacho', mission: 'Resultado de la misión', technical: 'Informe técnico de desempeño', returnShift: 'Volver al turno', endShift: 'Finalizar turno', next: 'Siguiente incidente', returnLobby: 'Volver al lobby', resultAlt: 'Resultado', hit: 'Acierto', error: 'Error', exemplary: 'Respuesta profesional ejemplar', safe: 'Incidente gestionado con seguridad', caveats: 'Resuelto con observaciones operativas', criticalFailures: 'Fallas críticas de protocolo', dispatchOk: 'Despacho compatible con el riesgo', dispatchLow: 'Despacho insuficiente', requiredSelected: 'Requerido: {required}. Seleccionado: {selected}.', criticalData: 'Recolección de datos críticos', criticalDataText: '{asked}/{total} protocolos relevantes confirmados antes del despacho. {coverageText}', responseTime: 'Tiempo de respuesta operativa', responseTimeText: 'Despacho en {time}. Ventana ideal: hasta {limit}.', proportional: 'Uso proporcional de recursos', excessive: 'Recurso posiblemente excesivo: {extra}.', noOverload: 'No hubo sobrecarga innecesaria de recursos.', escalation: 'Control del agravamiento', escalationText: 'Índice final de riesgo: {risk}/100.', queue: 'Gestión de cola del turno', queueText: 'Turno {shift}; {count} llamada(s) aún esperando triaje.', callManagement: 'Conducción de la llamada' },
    diagnostics: { systemOk: 'Sistema OK', alerts: '{count} alerta(s)', success: 'Todos los controles estructurales pasaron.', failures: 'Diagnóstico completado con {count} alerta(s).', auditOk: 'Auditoría interna completada sin fallas.', auditWarning: 'La auditoría interna encontró alertas.', labels: { build: 'Identificación de la build', content: 'Integridad del contenido', locales: 'Integridad de idiomas', dom: 'Componentes esenciales', storage: 'Almacenamiento local', backup: 'Copia de carrera', viewport: 'Viewport', serviceWorker: 'PWA / Service Worker', secureContext: 'Contexto seguro' }, details: { absent: 'ausente', incidentsValidated: '{count} incidentes validados', errors: '{count} error(es)', localesReady: 'PT-BR, EN-US y ES-419 completos', localeErrors: '{count} traducción(es) ausente(s)', missing: 'Ausentes: {items}', componentsFound: '{count} componentes encontrados', storageOps: 'lectura, escritura y eliminación probadas', backupAvailable: 'copia disponible', backupLater: 'se creará después del primer guardado', compatible: 'compatible', unavailable: 'no disponible', localFile: 'archivo local' } },
    notifications: { missingName: 'Escribe el nombre del operador.', fullscreenDenied: 'El navegador requiere instalar la app o no permite pantalla completa ahora.', saveFailure: 'No fue posible guardar. El juego sigue activo; exporta el diagnóstico.', resetConfirm: '¿Reiniciar carrera, copias y recuperación local de este navegador?', careerRemoved: 'Carrera local eliminada.', sessionSafe: 'Sesión estabilizada. Tus datos de carrera fueron preservados.', contentBlocked: 'Contenido bloqueado por la validación de seguridad. Abre Configuración.', shiftBlocked: 'El turno fue bloqueado porque falló la validación del contenido o de los idiomas.', shiftRecovered: 'Turno recuperado con seguridad.' },
    save: { invalidSave: 'Intento de guardar datos inválidos.', backupAutoRestored: 'El save principal era inválido; la copia se restauró automáticamente.', legacyMigrated: 'Save anterior {key} migrado a v0.18.0.', noBackup: 'No hay una copia íntegra disponible.', backupRestored: 'Copia restaurada correctamente.', backupInvalid: 'Copia inválida: {reason}' },
    recovery: { eyebrow: 'Protección antirotura activada', title: 'El juego encontró una falla inesperada', text: 'Tu progreso se conservó siempre que fue posible. Vuelve a una pantalla segura o recarga la aplicación.', code: 'Error de ejecución', safe: 'Volver con seguridad', reload: 'Recargar' },
    build: { phase: 'Fase 12 de 20', module: 'Turno continuo, cola viva e informe consolidado' }
  }
});
